FROM redis:8.8.0-alpine
LABEL maintainer="chenbz35@dimpt.com"

#COPY redis.conf /usr/local/etc/redis/redis.conf
RUN echo 'https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.23/main' > /etc/apk/repositories \
 && echo 'https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.23/community' >> /etc/apk/repositories \
 && apk update \
 && apk upgrade \
 && apk add fontconfig net-tools tzdata \
 && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
 && echo "Asia/Shanghai" > /etc/timezone \
 && rm -rf /var/cache/apk/*

ENV TZ=Asia/Shanghai
